---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    JOBS: 1
    secure: fOTO/HpUT0xsfml9iXuEL9qBu0NVErcig6CmrS1DFv7f4x9/mYQMNzLUv5b6VBPqGHeFNHiGaUUza3Ufc5KpL7DOu/1y6TFQlSoM6MRRdIXb+50MObvkJ4wXwYJH7Zrb4g8RTaBOY9uU5XQkm/E6GWWF3NiYFoVzCYPNSgAALko1caoEX2hoJNXJSd0T4G+gxtxc2g08RGunBPLqIyy2avMRN4yq0WDN2NbBrztM01FA5RoOLPyX0hhzyIZ+45z34wKvZtu7rj9h1KbFOZOVFJWpHDa0bXxhF63ldxPINe2QMOSsOD22Czk1+IKyC+88gtkvUq7pGUaJK6YdVDRcW9G/DMHVy/IE2aFabrPDVgzrmeCoVKzATzt8nMfIMTTu9Unoa5fdohpJ0NPhYnPfVAGfJ+2MPITgP+x2X6M5+KgHCBdaIgwBVnZE9DTb1L9c/Eh50zeHHbfv9L+NVlbQFzMWNj+kKWMj0qwh6JPpSFiKaOvTK6XP+NSUc7euAZgqK6lwqS07pvcql4qvzbeRWyn/GZuRHOGvfkUNuvLee8dMKfpF3s1VQ6blHHqKB8qH2ifxawiztWgUkYxK0GFTk//ZopLzP90bLl0JiGlg517tp5V9eBOK5ZlPwsSOhD+wta9gCssPjK4i2H2IwLox7AqXegigBMdqIbXz9LaFVAY=

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/
    # greenkeeper branches
    - /^greenkeeper\/.*$/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - COVERAGE=true yarn test
        - codecov

    # - name: "Floating Dependencies"
    #   script:
    #     - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codecov

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO

notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
  slack:
    rooms:
      secure: Iow+t6PxSdOWATEgcWjN9tNCFdnaDi87LbQcOZHqwutYs9jmXe6vszMmqRRKaiUTHQN/uSRZ6CrxEjC9vD9IaBSRORi8UcnXlZ+C0cfcbuiAdb4SWXKoXssGdZMdmS8fl+LRA7UGGfy//OwKAgr71Z/Re/WGRiqhM89vvVgOzkhpglA/gYUM5RYyu1FC+IEwE3NpHWYgtq0gtbvWso2V5C7Uqv8OfUJAckgcfyrm7lpSzY6XJiRiN6fAKJGxTg56BnQF0IpZKjL66jUbMSlnYkvlV/dMBX15NIvEwN4ZnQfkfitNipEvmGKkOJgQeNMp52fgP5J57esSCgWM0o2vhDJZbJWSgZsV2ZQzFHifmSUysmWYoouN/vi6I1lmQ9yGslkzn1gFxRTZjmbc55dLclmKyOtKufhEl/jyHaHoqDGVT2Yb2+8sNP2NTlERdsVF1/uBg+jU+/wIvFaF44qibswRK+m5FB3jnNl7exx+s8fHqvk5GH8NgI7oPwKI4+nwi++HvBBJHxsulrpFn3ALklvIF+eSRwso1LTFVk7EHJUt7SeLhKY2PXh7U9OlFuuNp2c3sq8h+f8dliv2u3GuyteAW+zbTVU7bA6rXYOHWoSqlzf3JB8/D70lCwEm768dyh7APz/xgJdC3vZGm8kChxQB+EWGH7aeWowSZxa+JxM=

deploy:
  provider: npm
  skip_cleanup: true
  email: devo.tox.89@gmail.com
  api_key:
    secure: moE/H3rJTsJm38OeGtonJ6LQOq0TGsSH97b6JmJMaaNq4/1HVU3v10pX3qLRXVX2B+Z/SJpoLUGhw6cNKFqtxqdTH3045Hj8SIStO3teXgQyb1i+mUdwuHjEmYo57iJt75+OvxV8CGACoT6s8nx7Of6c9HVqWKLRf2FnRMCCeF2Hep04Aqb89ak+2+fttCJqpl8pWAJ51esypi3Nb/EYenDBp4gTRQLlzdAelshJYSsgywYaS7LBYBbyBWqRFM0sK5Pt4lv6Kv7vHDQelg21+1dOt0E+8hAacQe/cEBPyWR8RAObrcaQwORQsW1i6ecYxR2ZPEZw8wh1HWUKGVDnYgI1+NHHjcvoqPadIBVm7mm+d3Au0bkp1uJty2fPFBpwYh5e6+x/+o+QJk6bPRBMTp6WFETgPjaihUob+8/8yR/ZvQsaWue5U6ULFgblvWyip1lkuk3Uw7muu5B4DAzrEq7CjlHPPBSa+2qG5WB9LTtRyxXAoCyzYnWlxJBnv7KvUuPqINzoZOCGxIX7WQa5GSe6aXMJKWxFyYXvNQj6IoFtR+/HINhr3KBIhM/NYiJEt+WejA0CIB4w6/kI6XtomSg/K2FA/gNgc+kVjllDqHyvYPp7c3xRibI+1j46gRuybUkL8mN1i5Py0SroqZy9gN+KcRxWE0cBloMuut+x+Tk=
  on:
    tags: true
    repo: devotox/ember-cli-pushjs
